USER root

#=========
# Firefox
#=========
RUN apt-get update -qqy \
  && apt-get -qqy install firefox-esr libavcodec-extra \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

ARG TARGETARCH

#============
# GeckoDriver
#============
# For arm64 we're sniffing a compatible binary out of an ubuntu package, don't look too hard!
RUN if [ "$(TARGETARCH)" = "arm64" ]; then \
    curl http://ports.ubuntu.com/pool/universe/f/firefox/firefox-geckodriver_89.0.2+build1-0ubuntu1_arm64.deb | dpkg-deb --fsys-tarfile - | tar -C / -x ./usr/bin/geckodriver; \
  else \
    wget --no-verbose -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz \
    && rm -rf /opt/geckodriver \
    && tar -C /opt -zxf /tmp/geckodriver.tar.gz \
    && rm /tmp/geckodriver.tar.gz \
    && mv /opt/geckodriver /opt/geckodriver-0.29.1 \
    && chmod 755 /opt/geckodriver-0.29.1 \
    && ln -fs /opt/geckodriver-0.29.1 /usr/bin/geckodriver; \
  fi

USER 1200

RUN echo "firefox" > /opt/selenium/browser_name
