apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/alvarogg777/argo-combined-demo/master/argo-workflows/overlays/production/regcred.yaml
- selenium-grid.yaml
#patchesStrategicMerge:
#- patch-grid.yaml
patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets/-
      value:
        name: regcred
namespace: selenium-system
